[package]
name = "drivers"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"

[dependencies]
anyhow = "1.0.86"
chrono = { version = "0.4.38", features = ["serde"] }
clap = { version = "4.5.7", features = ["derive"] }
csv = "1.3.0"
db-dump = "0.7.4"
schemars = { version = "1.0.0-alpha.2", features = ["chrono04", "semver1", "url2"] }
semver = { version = "1.0.23", features = ["serde"] }
serde = { version = "1.0.205", features = ["derive"] }
serde_json = "1.0.117"
spdx = "0.10.4"
toml = "0.8.14"
url = { version = "2.5.2", features = ["serde"] }
