[package]
name = "drivers"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1.0.99"
chrono = { version = "0.4.42", features = ["serde"] }
clap = { version = "4.5.47", features = ["derive"] }
csv = "1.3.1"
db-dump = "0.7.13"
schemars = { version = "1.0.4", features = ["chrono04", "semver1", "url2"] }
semver = { version = "1.0.26", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
spdx = "0.12.0"
toml = "0.9.5"
url = { version = "2.5.7", features = ["serde"] }
