# TODO: This is mock data! Check before using!
manifest_version = "0.0.1"

[meta]
names = ["lis3dh"]
manufacturer = "ST"
datasheets = ["https://www.st.com/resource/en/datasheet/lis3dh.pdf"]
categories = ["Sensor::Accelerometer"]
part_numbers = ["LIS3DHHTR", "LIS3DHTR", "LIS3DHLTR"]

kicad_symbol = ["Sensor_Motion::LIS3DH"]
packages = ["LGA-16"]

[dev_boards]
adafruit = 2809
sparkfun = 13963
mikroe = 1905

[interfaces.i2c]
addrs = [0x18, 0x19]
interrupt = true
